# Generated by Django 5.2.5 on 2026-03-24 15:00

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Library',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('userId', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=50, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('SUSPENDED', 'Suspended')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('songId', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('artist', models.CharField(max_length=100)),
                ('duration', models.IntegerField()),
                ('genre', models.CharField(choices=[('POP', 'Pop'), ('JAZZ', 'Jazz'), ('ROCK', 'Rock'), ('HIPHOP', 'HipHop'), ('CLASSICAL', 'Classical'), ('ROMANCE', 'Romance')], max_length=20)),
                ('library', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='songs', to='songs.library')),
            ],
        ),
        migrations.CreateModel(
            name='Folder',
            fields=[
                ('folderId', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subfolders', to='songs.folder')),
                ('library', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='folders', to='songs.library')),
                ('songs', models.ManyToManyField(blank=True, related_name='folders', to='songs.song')),
            ],
        ),
        migrations.AddField(
            model_name='library',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='library', to='songs.user'),
        ),
    ]
